# coding:utf-8

OK                  = "0"           # u"成功"
DBERR               = "4001"        # u"数据库查询错误"
NODATA              = "4002"        # u"无数据"
DATAEXIST           = "4003"        # u"数据已存在"
DATAERR             = "4004"        # u"数据错误"
SESSIONERR          = "4101"        # u"用户未登录"
LOGINERR            = "4102"        # u"用户登录失败"
PARAMERR            = "4103"        # u"参数错误"
USERERR             = "4104"        # u"用户不存在或未激活"
ROLEERR             = "4105"        # u"用户身份错误"
PWDERR              = "4106"        # u"密码错误"
REQERR              = "4201"        # u"非法请求或请求次数受限"
IPERR               = "4202"        # u"IP受限"
THIRDERR            = "4301"        # u"第三方系统错误"
IOERR               = "4302"        # u"文件读写错误"
SERVERERR           = "4500"        # u"内部错误"
UNKOWNERR           = "4501"        # u"未知错误"
